- name: Ensure that HAProxy is installed
  import_tasks: install_haproxy.yml
  tags:
    - hainstall
    - standalone
    - cluster

- name: Ensure that Keepalived is installed
  import_tasks: install_keepalived.yml
  tags:
    - kainstall
    - cluster

- name: Ensure that inotify is installed
  import_tasks: install_inotify.yml
  tags:
    - ininstall
    - cluster